#!/bin/bash
# see wget https://raw.githubusercontent.com/longhorn/longhorn/v1.8.1/deploy/longhorn-images.txt

LONGHORN_RELEASE=v1.8.1
LONGHORN_URL=https://raw.githubusercontent.com/longhorn/longhorn/${LONGHORN_RELEASE}

# deploy
wget -O files/longhorn/environment_check.sh ${LONGHORN_URL}/scripts/environment_check.sh
wget -O files/longhorn/longhorn.yaml ${LONGHORN_URL}/deploy/longhorn.yaml
# mirror
wget -O files/longhorn/save-images.sh ${LONGHORN_URL}/scripts/save-images.sh
wget -O files/longhorn/load-images.sh ${LONGHORN_URL}/scripts/load-images.sh
wget -O files/longhorn/images.txt wget ${LONGHORN_URL}/deploy/longhorn-images.txt
# uninstall
wget -O files/longhorn/uninstall.yaml wget ${LONGHORN_URL}/uninstall/uninstall.yaml
