#!/bin/bash

METALLB_RELEASE=v0.15.2
METALLB_URL=https://raw.githubusercontent.com/metallb/metallb/${METALLB_RELEASE}

# deploy
wget -O files/metallb/metallb-native.yaml ${METALLB_URL}/config/manifests/metallb-native.yaml
