- name: push metallb config template (present)
  become: false
  connection: local
  local_action:
    module: ansible.builtin.template
    mode: 0600
    src: metallb.yaml.j2
    dest: "{{_k3s_debug_path}}/metallb.yaml"
  vars:
    _pools: >-
      {{ (_k3s_cfg.metallb.pools|default({})|dict2items|rejectattr('value.state','defined')|list +
          _k3s_cfg.metallb.pools|default({})|dict2items|selectattr('value.state','defined')|rejectattr('value.state','equalto','absent')|list)
         | items2dict }}
    _advertisements: >-
      {{ (_k3s_cfg.metallb.advertisements|default({})|dict2items|rejectattr('value.state','defined')|list +
          _k3s_cfg.metallb.advertisements|default({})|dict2items|selectattr('value.state','defined')|rejectattr('value.state','equalto','absent')|list)
         | items2dict }}
    _bgp_peers: >-
      {{ (_k3s_cfg.metallb.bgp_peers|default({})|dict2items|rejectattr('value.state','defined')|list +
          _k3s_cfg.metallb.bgp_peers|default({})|dict2items|selectattr('value.state','defined')|rejectattr('value.state','equalto','absent')|list)
         | items2dict }}
  when: _k3s_debug_path is defined

- name: push metallb config template (absent)
  become: false
  connection: local
  local_action:
    module: ansible.builtin.template
    mode: 0600
    src: metallb.yaml.j2
    dest: "{{_k3s_debug_path}}/metallb-remove.yaml"
  vars:
    _pools: "{{_k3s_cfg.metallb.pools|default({})|dict2items|selectattr('value.state','defined')|selectattr('value.state','equalto','absent')|items2dict}}"
    _advertisements: "{{_k3s_cfg.metallb.advertisements|default({})|dict2items|selectattr('value.state','defined')|selectattr('value.state','equalto','absent')|items2dict}}"
    _bgp_peers: "{{_k3s_cfg.metallb.bgp_peers|default({})|dict2items|selectattr('value.state','defined')|selectattr('value.state','equalto','absent')|items2dict}}"
  when: _k3s_debug_path is defined

- name: deploy metallb
  kubernetes.core.k8s:
    kubeconfig: "{{_k3s_kubecfg}}"
    state: present
    definition: "{{lookup('file', 'metallb/metallb-native.yaml')}}"

- name: wait for metallb webhook to be ready
  kubernetes.core.k8s_info:
    kubeconfig: "{{_k3s_kubecfg}}"
    kind: Deployment
    name: controller
    namespace: metallb-system
  register: _metallb_controller
  until: >
    _metallb_controller.resources | length > 0 and
    (_metallb_controller.resources[0].status.availableReplicas | default(0)) > 0
  retries: 24
  delay: 5

- name: remove metallb pools and advertisements
  kubernetes.core.k8s:
    kubeconfig: "{{_k3s_kubecfg}}"
    state: absent
    definition: "{{lookup('template', 'metallb.yaml.j2')}}"
  vars:
    _pools: "{{_k3s_cfg.metallb.pools|default({})|dict2items|selectattr('value.state','defined')|selectattr('value.state','equalto','absent')|items2dict}}"
    _advertisements: "{{_k3s_cfg.metallb.advertisements|default({})|dict2items|selectattr('value.state','defined')|selectattr('value.state','equalto','absent')|items2dict}}"
    _bgp_peers: "{{_k3s_cfg.metallb.bgp_peers|default({})|dict2items|selectattr('value.state','defined')|selectattr('value.state','equalto','absent')|items2dict}}"
  when: >
    (_pools | length > 0) or
    (_advertisements | length > 0) or
    (_bgp_peers | length > 0)

- name: deploy metallb pools
  kubernetes.core.k8s:
    kubeconfig: "{{_k3s_kubecfg}}"
    state: present
    apply: yes
    definition: "{{lookup('template', 'metallb.yaml.j2')}}"
  vars:
    _pools: >-
      {{ (_k3s_cfg.metallb.pools|default({})|dict2items|rejectattr('value.state','defined')|list +
          _k3s_cfg.metallb.pools|default({})|dict2items|selectattr('value.state','defined')|rejectattr('value.state','equalto','absent')|list)
         | items2dict }}
    _advertisements: >-
      {{ (_k3s_cfg.metallb.advertisements|default({})|dict2items|rejectattr('value.state','defined')|list +
          _k3s_cfg.metallb.advertisements|default({})|dict2items|selectattr('value.state','defined')|rejectattr('value.state','equalto','absent')|list)
         | items2dict }}
    _bgp_peers: >-
      {{ (_k3s_cfg.metallb.bgp_peers|default({})|dict2items|rejectattr('value.state','defined')|list +
          _k3s_cfg.metallb.bgp_peers|default({})|dict2items|selectattr('value.state','defined')|rejectattr('value.state','equalto','absent')|list)
         | items2dict }}
