- name: deploy network policies
  kubernetes.core.k8s:
    kubeconfig: "{{_k3s_kubecfg}}"
    state: present
    apply: yes
    definition: "{{lookup('template', 'network-policies.yaml.j2')}}"
  vars:
    _np_cfg: "{{_k3s_cfg.network_policies}}"
