- name: set default password store
  set_fact:
    k3s_passdb: "{{passdb|default('passwordstore')}}"
  when: k3s_passdb is undefined

- name: load k3s config from k3s_clusters variable
  set_fact:
    _k3s_cfg: "{{k3s_clusters[k3s_cluster]}}"
  when: >
    _k3s_cfg is undefined and
    k3s_cluster is defined and
    k3s_clusters is defined and
    k3s_clusters[k3s_cluster] is defined

- name: load k3s config from k3s variable
  set_fact:
    _k3s_cfg: "{{k3s}}"
  when: >
    _k3s_cfg is undefined and
    k3s is defined

- include_tasks: k3s_setup.yml
  when: _k3s_cfg is defined

- set_fact:
    role_packages:
      - "python{{python_version}}-kubernetes"
      - nfs-client
      - open-iscsi
  when: >
    (ansible_os_family == "Suse" or
    ansible_os_family == "openSUSE MicroOS") and
    python_version is defined

- include_role:
    name: data-utilities
    tasks_from: install_packages
  when: role_packages is defined

- include_tasks: test_cluster.yml
  when: >
    _k3s_cfg is defined and
    _k3s_cfg.test_cluster is defined and
    _k3s_cfg.test_cluster == true
