- name: set default password store
  set_fact:
    k3s_passdb: "{{passdb|default('passwordstore')}}"
  when: k3s_passdb is undefined

- name: set default kubeconfig location
  set_fact:
    _k3s_kubecfg: /etc/rancher/k3s/k3s.yaml

- name: load k3s config from k3s_clusters variable
  set_fact:
    _k3s_cfg: "{{k3s_clusters[k3s_cluster]}}"
  when: >
    _k3s_cfg is undefined and
    k3s_cluster is defined and
    k3s_clusters is defined and
    k3s_clusters[k3s_cluster] is defined

- name: load k3s config from k3s variable
  set_fact:
    _k3s_cfg: "{{k3s}}"
  when: >
    _k3s_cfg is undefined and
    k3s is defined

- name: set kubeconfig location override
  set_fact:
    _k3s_kubecfg: "{{_k3s_cfg.kubecfg}}"
  when: >-
    _k3s_cfg is defined and
    _k3s_cfg.kubecfg is defined

- include_tasks: k3s_setup.yml
  when: _k3s_cfg is defined

- set_fact:
    role_packages:
      - "python{{python_version}}-kubernetes"
      - nfs-client
      - open-iscsi
  when: >
    (ansible_os_family == "Suse" or
    ansible_os_family == "openSUSE MicroOS") and
    python_version is defined

- include_role:
    name: data-utilities
    tasks_from: install_packages
  when: role_packages is defined

- include_tasks: test_cluster.yml
  when: >
    _k3s_cfg is defined and
    _k3s_cfg.test_cluster is defined and
    _k3s_cfg.test_cluster == true and
    k3s_role|default('agent') == 'server'

- include_tasks: deploy_longhorn.yml
  when: >
    _k3s_cfg is defined and
    _k3s_cfg.longhorn is defined and
    _k3s_cfg.longhorn.state is defined and
    _k3s_cfg.longhorn.state == 'present' and
    k3s_role|default('agent') == 'server'

- include_tasks: remove_longhorn.yml
  when: >
    _k3s_cfg is defined and
    _k3s_cfg.longhorn is defined and
    _k3s_cfg.longhorn.state is defined and
    _k3s_cfg.longhorn.state == 'absent' and
    k3s_role|default('agent') == 'server'
